NAME = mavlink_control

# Sources
SRC = src

# Includes
INCLUDE = inc/

# MAVLink library
MAVLIB = mavlink/include/mavlink/v1.0/

OBJS = $(NAME).o interface.o serial_port_pc.o

all: $(NAME)

$(NAME): $(OBJS)
	g++ $(OBJS) -o $(NAME) 

$(NAME).o: $(SRC)/$(NAME).cpp
	g++ -I$(INCLUDE) -I$(MAVLIB) -c $(SRC)/$(NAME).cpp
	g++ -I$(INCLUDE) -I$(MAVLIB) -c $(SRC)/interface.cpp
	g++ -I$(INCLUDE) -I$(MAVLIB) -c $(SRC)/serial_port_pc.cpp

clean:
	rm *.o $(NAME)
